spring.application.name=RegistroTreinos

spring.datasource.url=jdbc:mysql://localhost:3306/registrotreinos
spring.datasource.username=root
spring.datasource.password=Dumar@1110

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true